server:
  port: 8080
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://fntywpwiatkhqw:90e568a2d66de75f66579c1fb967e7a5488c2da583801158d23c96fa38b5c1ab@ec2-52-0-114-209.compute-1.amazonaws.com:5432/d30ufdk3n21cgq
    username: fntywpwiatkhqw
    password: 90e568a2d66de75f66579c1fb967e7a5488c2da583801158d23c96fa38b5c1ab
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Bootcamp - my first project Backend
